export const LANGUAGES = {
  en: 'English',
  ar: 'العربية',
  uk: 'Українська',
  es: 'Español',
  fr: 'Français',
  tr: 'Türkçe',
};

export const T = {
  appName: 'SafeMind',
  tagline: 'You are not alone. Help is here.',
  subtitle: 'A free mental health first-response tool for people affected by conflict and crisis.',
  moodQ: 'How are you feeling right now?',
  moods: ['Terrified', 'Anxious', 'Numb', 'Sad', 'Angry', 'Hopeful'],
  moodEmoji: ['😨', '😰', '😶', '😢', '😠', '🌱'],
  tabs: ['Check-in', 'Breathe', 'Grounding', 'Screening', 'Resources'],
  tabIcons: ['💚', '🌬', '🌍', '📋', '🤝'],
  breatheDesc: 'This simple exercise can help calm your nervous system. Follow the circle.',
  inhale: 'Breathe In',
  hold: 'Hold',
  exhale: 'Breathe Out',
  rest: 'Rest',
  start: 'Start Breathing',
  stop: 'Pause',
  groundDesc: 'This technique helps bring you back to the present moment when you feel overwhelmed.',
  groundSteps: [
    { n: 5, sense: 'things you can SEE', icon: '👁' },
    { n: 4, sense: 'things you can TOUCH', icon: '✋' },
    { n: 3, sense: 'things you can HEAR', icon: '👂' },
    { n: 2, sense: 'things you can SMELL', icon: '👃' },
    { n: 1, sense: 'thing you can TASTE', icon: '👅' },
  ],
  groundPlaceholder: 'Type what you notice...',
  groundNext: 'Next →',
  groundDone: 'Well done. You are here. You are safe in this moment.',
  screenDesc: 'These questions help us understand what you\'re experiencing. There are no wrong answers.',
  screenQuestions: [
    'Do you have trouble sleeping or have nightmares?',
    'Do you feel on edge or easily startled?',
    'Do you avoid places or situations that remind you of a traumatic event?',
    'Do you feel emotionally numb or detached from others?',
    'Do you experience flashbacks or intrusive memories?',
    'Do you feel hopeless about the future?',
    'Have you lost interest in activities you used to enjoy?',
    'Do you have difficulty concentrating?',
  ],
  screenOptions: ['Never', 'Sometimes', 'Often', 'Always'],
  screenSubmit: 'See Results',
  screenLow: 'Your responses suggest you\'re coping relatively well. Continue practicing self-care and reach out if things change.',
  screenMid: 'Your responses suggest moderate distress. We recommend connecting with a mental health professional. The coping tools here can help in the meantime.',
  screenHigh: 'Your responses suggest significant distress. Please reach out to a professional or crisis line. You deserve support — help is available right now.',
  resourceDesc: 'These organizations provide free, confidential support.',
  resources: [
    { name: 'WHO Mental Health', desc: 'World Health Organization resources for crisis-affected populations', url: 'https://www.who.int/health-topics/mental-health' },
    { name: 'UNHCR Counseling', desc: 'Mental health support for refugees and displaced persons', url: 'https://www.unhcr.org/mental-health' },
    { name: 'Crisis Text Line', desc: 'Free 24/7 text-based crisis support', url: 'https://www.crisistextline.org', phone: 'Text HOME to 741741' },
    { name: 'International Medical Corps', desc: 'Mental health programs in conflict zones', url: 'https://internationalmedicalcorps.org' },
    { name: 'MSF Psychological Support', desc: 'Médecins Sans Frontières mental health services', url: 'https://www.msf.org' },
    { name: 'IASC Guidelines', desc: 'Inter-Agency Standing Committee mental health in emergencies', url: 'https://interagencystandingcommittee.org' },
  ],
  safetyNotice: 'If you are in immediate danger, please contact local emergency services.',
  crisisLine: 'Crisis support available 24/7',
  checkinResponse: {
    0: 'Fear is a natural response to danger. You are showing courage by being here. Let\'s work through this together.',
    1: 'Anxiety can feel overwhelming, but it can be managed. Let\'s try some techniques to help calm your body and mind.',
    2: 'Feeling numb is your mind\'s way of protecting you. It\'s okay. Gentle steps can help you reconnect safely.',
    3: 'Your sadness is valid. Grief and loss are heavy burdens. You don\'t have to carry them alone.',
    4: 'Anger is a natural response to injustice and loss. Let\'s find healthy ways to process what you\'re feeling.',
    5: 'Hope is powerful, even in small amounts. Let\'s nurture that feeling and build on it together.',
  },
  suggest: 'We suggest trying:',
  tryLabels: ['Guided Breathing →', 'Grounding Exercise →', 'Quick Screening →', 'Talk to Someone →'],
  resetMood: '← Check in again',
  footer: 'SafeMind is not a substitute for professional care. If in crisis, contact emergency services.',
};

export const styles = {
  sectionDesc: {
    color: '#5a6e5a',
    fontSize: 15,
    lineHeight: 1.7,
    maxWidth: 420,
    margin: '0 auto 28px',
    textAlign: 'center',
  },
  card: {
    background: 'rgba(255,255,255,0.45)',
    borderRadius: 18,
    padding: 28,
    maxWidth: 420,
    margin: '0 auto',
    border: '1px solid rgba(139,176,132,0.12)',
    backdropFilter: 'blur(8px)',
  },
  textarea: {
    width: '100%',
    padding: 14,
    borderRadius: 12,
    border: '1px solid rgba(139,176,132,0.25)',
    background: 'rgba(255,255,255,0.6)',
    resize: 'none',
    fontSize: 14,
    color: '#3a5a35',
    boxSizing: 'border-box',
    fontFamily: "'DM Sans', sans-serif",
    lineHeight: 1.6,
  },
  primaryBtn: {
    padding: '13px 36px',
    borderRadius: 28,
    border: 'none',
    cursor: 'pointer',
    background: 'linear-gradient(135deg, #7aaa6e 0%, #5a8e52 100%)',
    color: '#fff',
    fontSize: 15,
    fontWeight: 700,
    letterSpacing: 0.3,
    boxShadow: '0 4px 16px rgba(90,142,82,0.2)',
    transition: 'all 0.3s',
  },
  secondaryBtn: {
    padding: '10px 22px',
    borderRadius: 24,
    cursor: 'pointer',
    border: '1.5px solid rgba(122,170,110,0.3)',
    background: 'rgba(255,255,255,0.5)',
    color: '#3a6a30',
    fontSize: 14,
    fontWeight: 600,
    transition: 'all 0.25s',
  },
  linkBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#7aaa6e',
    fontSize: 13,
    fontWeight: 600,
    padding: 0,
  },
};
