export const LANGUAGES = {
  en: 'English',
  hi: 'हिन्दी',
  tl: 'Tagalog',
  ar: 'العربية',
  uk: 'Українська',
  es: 'Español',
  fr: 'Français',
  tr: 'Türkçe',
};

const TRANSLATIONS = {
  en: {
    appName: 'SafeMind', tagline: 'You are not alone. Help is here.',
    subtitle: 'A free mental health first-response tool for people affected by conflict and crisis.',
    moodQ: 'How are you feeling right now?',
    moods: ['Terrified', 'Anxious', 'Numb', 'Sad', 'Angry', 'Hopeful'],
    moodEmoji: ['😨', '😰', '😶', '😢', '😠', '🌱'],
    tabs: ['Check-in', 'Breathe', 'Grounding', 'Screening', 'Resources'],
    tabIcons: ['💚', '🌬', '🌍', '📋', '🤝'],
    breatheDesc: 'This simple exercise can help calm your nervous system. Follow the circle.',
    inhale: 'Breathe In', hold: 'Hold', exhale: 'Breathe Out', rest: 'Rest',
    start: 'Start Breathing', stop: 'Pause',
    groundDesc: 'This technique helps bring you back to the present moment when you feel overwhelmed.',
    groundSteps: [
      { n: 5, sense: 'things you can SEE', icon: '👁' }, { n: 4, sense: 'things you can TOUCH', icon: '✋' },
      { n: 3, sense: 'things you can HEAR', icon: '👂' }, { n: 2, sense: 'things you can SMELL', icon: '👃' },
      { n: 1, sense: 'thing you can TASTE', icon: '👅' },
    ],
    groundPlaceholder: 'Type what you notice...', groundNext: 'Next →', groundComplete: '✓ Complete',
    groundDone: 'Well done. You are here. You are safe in this moment.', groundTryAgain: 'Try Again', groundName: 'Name',
    screenDesc: 'These questions help us understand what you\'re experiencing. There are no wrong answers.',
    screenQuestions: [
      'Do you have trouble sleeping or have nightmares?', 'Do you feel on edge or easily startled?',
      'Do you avoid places or situations that remind you of a traumatic event?',
      'Do you feel emotionally numb or detached from others?', 'Do you experience flashbacks or intrusive memories?',
      'Do you feel hopeless about the future?', 'Have you lost interest in activities you used to enjoy?',
      'Do you have difficulty concentrating?',
    ],
    screenOptions: ['Never', 'Sometimes', 'Often', 'Always'], screenSubmit: 'See Results', screenRetake: 'Retake',
    screenLow: 'Your responses suggest you\'re coping relatively well. Continue practicing self-care and reach out if things change.',
    screenMid: 'Your responses suggest moderate distress. We recommend connecting with a mental health professional. The coping tools here can help in the meantime.',
    screenHigh: 'Your responses suggest significant distress. Please reach out to a professional or crisis line. You deserve support — help is available right now.',
    viewResources: 'View Resources →',
    resourceDesc: 'These organizations provide free, confidential support.',
    resources: [
      { name: 'WHO Mental Health', desc: 'World Health Organization resources for crisis-affected populations', url: 'https://www.who.int/health-topics/mental-health' },
      { name: 'UNHCR Counseling', desc: 'Mental health support for refugees and displaced persons', url: 'https://www.unhcr.org/mental-health' },
      { name: 'Crisis Text Line', desc: 'Free 24/7 text-based crisis support', url: 'https://www.crisistextline.org', phone: 'Text HOME to 741741' },
      { name: 'International Medical Corps', desc: 'Mental health programs in conflict zones', url: 'https://internationalmedicalcorps.org' },
      { name: 'MSF Psychological Support', desc: 'Médecins Sans Frontières mental health services', url: 'https://www.msf.org' },
      { name: 'IASC Guidelines', desc: 'Inter-Agency Standing Committee mental health in emergencies', url: 'https://interagencystandingcommittee.org' },
    ],
    safetyNotice: 'If you are in immediate danger, please contact local emergency services.',
    crisisLine: 'Crisis support available 24/7',
    checkinResponse: {
      0: 'Fear is a natural response to danger. You are showing courage by being here. Let\'s work through this together.',
      1: 'Anxiety can feel overwhelming, but it can be managed. Let\'s try some techniques to help calm your body and mind.',
      2: 'Feeling numb is your mind\'s way of protecting you. It\'s okay. Gentle steps can help you reconnect safely.',
      3: 'Your sadness is valid. Grief and loss are heavy burdens. You don\'t have to carry them alone.',
      4: 'Anger is a natural response to injustice and loss. Let\'s find healthy ways to process what you\'re feeling.',
      5: 'Hope is powerful, even in small amounts. Let\'s nurture that feeling and build on it together.',
    },
    suggest: 'We suggest trying:',
    tryLabels: ['Guided Breathing →', 'Grounding Exercise →', 'Quick Screening →', 'Talk to Someone →'],
    resetMood: '← Check in again',
    footer: 'SafeMind is not a substitute for professional care. If in crisis, contact emergency services.',
    brand: 'A Roseleap Initiative', brandUrl: 'https://roseleap.com',
    begin: 'Begin', ready: 'Ready', cycle: 'Cycle', completed: 'Completed',
    cyclesDone: 'cycles. Great work.', cycleDone: 'cycle. Great work.',
  },
  ar: {
    appName: 'سيف مايند', tagline: 'لست وحدك. المساعدة هنا.',
    subtitle: 'أداة مجانية للاستجابة الأولية للصحة النفسية للأشخاص المتأثرين بالنزاعات والأزمات.',
    moodQ: 'كيف تشعر الآن؟',
    moods: ['مرعوب', 'قلق', 'مخدّر', 'حزين', 'غاضب', 'متفائل'],
    moodEmoji: ['😨', '😰', '😶', '😢', '😠', '🌱'],
    tabs: ['تسجيل الحالة', 'تنفس', 'تأريض', 'فحص', 'موارد'],
    tabIcons: ['💚', '🌬', '🌍', '📋', '🤝'],
    breatheDesc: 'هذا التمرين البسيط يمكن أن يساعد في تهدئة جهازك العصبي. اتبع الدائرة.',
    inhale: 'شهيق', hold: 'احبس', exhale: 'زفير', rest: 'راحة',
    start: 'ابدأ التنفس', stop: 'توقف',
    groundDesc: 'هذه التقنية تساعدك على العودة إلى اللحظة الحالية عندما تشعر بالإرهاق.',
    groundSteps: [
      { n: 5, sense: 'أشياء يمكنك رؤيتها', icon: '👁' }, { n: 4, sense: 'أشياء يمكنك لمسها', icon: '✋' },
      { n: 3, sense: 'أشياء يمكنك سماعها', icon: '👂' }, { n: 2, sense: 'أشياء يمكنك شمها', icon: '👃' },
      { n: 1, sense: 'شيء يمكنك تذوقه', icon: '👅' },
    ],
    groundPlaceholder: 'اكتب ما تلاحظه...', groundNext: 'التالي →', groundComplete: '✓ اكتمل',
    groundDone: 'أحسنت. أنت هنا. أنت آمن في هذه اللحظة.', groundTryAgain: 'حاول مرة أخرى', groundName: 'اذكر',
    screenDesc: 'هذه الأسئلة تساعدنا على فهم ما تمر به. لا توجد إجابات خاطئة.',
    screenQuestions: [
      'هل تعاني من صعوبة في النوم أو كوابيس؟', 'هل تشعر بالتوتر أو تنزعج بسهولة؟',
      'هل تتجنب الأماكن أو المواقف التي تذكرك بحدث مؤلم؟', 'هل تشعر بالخدر العاطفي أو الانفصال عن الآخرين؟',
      'هل تعاني من ذكريات مقتحمة أو استرجاعات؟', 'هل تشعر باليأس تجاه المستقبل؟',
      'هل فقدت الاهتمام بالأنشطة التي كنت تستمتع بها؟', 'هل تعاني من صعوبة في التركيز؟',
    ],
    screenOptions: ['أبداً', 'أحياناً', 'غالباً', 'دائماً'], screenSubmit: 'عرض النتائج', screenRetake: 'إعادة',
    screenLow: 'تشير إجاباتك إلى أنك تتأقلم بشكل جيد. استمر في الاعتناء بنفسك وتواصل إذا تغيرت الأمور.',
    screenMid: 'تشير إجاباتك إلى ضائقة متوسطة. نوصي بالتواصل مع متخصص. أدوات التأقلم هنا يمكن أن تساعد.',
    screenHigh: 'تشير إجاباتك إلى ضائقة كبيرة. يرجى التواصل مع متخصص أو خط أزمات. أنت تستحق الدعم.',
    viewResources: 'عرض الموارد →',
    resourceDesc: 'هذه المنظمات تقدم دعماً مجانياً وسرياً.',
    resources: [
      { name: 'منظمة الصحة العالمية', desc: 'موارد الصحة النفسية للسكان المتأثرين بالأزمات', url: 'https://www.who.int/health-topics/mental-health' },
      { name: 'المفوضية السامية للاجئين', desc: 'دعم الصحة النفسية للاجئين والنازحين', url: 'https://www.unhcr.org/mental-health' },
      { name: 'خط الأزمات', desc: 'دعم مجاني على مدار الساعة', url: 'https://www.crisistextline.org', phone: 'أرسل HOME إلى 741741' },
      { name: 'الفيلق الطبي الدولي', desc: 'برامج الصحة النفسية في مناطق النزاع', url: 'https://internationalmedicalcorps.org' },
      { name: 'أطباء بلا حدود', desc: 'خدمات الدعم النفسي', url: 'https://www.msf.org' },
      { name: 'إرشادات اللجنة الدائمة', desc: 'الصحة النفسية في حالات الطوارئ', url: 'https://interagencystandingcommittee.org' },
    ],
    safetyNotice: 'إذا كنت في خطر فوري، يرجى الاتصال بخدمات الطوارئ المحلية.',
    crisisLine: 'دعم الأزمات متاح على مدار الساعة',
    checkinResponse: {
      0: 'الخوف استجابة طبيعية للخطر. أنت تُظهر شجاعة بوجودك هنا. دعنا نعمل معاً.',
      1: 'القلق قد يكون مرهقاً، لكن يمكن التعامل معه. دعنا نجرب بعض التقنيات لتهدئة جسمك وعقلك.',
      2: 'الشعور بالخدر هو طريقة عقلك لحمايتك. لا بأس. خطوات لطيفة يمكن أن تساعدك.',
      3: 'حزنك مشروع. الحزن والفقدان أعباء ثقيلة. لا يجب أن تحملها وحدك.',
      4: 'الغضب استجابة طبيعية للظلم. دعنا نجد طرقاً صحية لمعالجة ما تشعر به.',
      5: 'الأمل قوي، حتى بكميات صغيرة. دعنا نغذي هذا الشعور معاً.',
    },
    suggest: 'نقترح تجربة:', tryLabels: ['تمارين التنفس →', 'تمرين التأريض →', 'فحص سريع →', 'تحدث مع شخص →'],
    resetMood: '← تسجيل مرة أخرى',
    footer: 'سيف مايند ليس بديلاً عن الرعاية المهنية. في حالة الأزمة، اتصل بخدمات الطوارئ.',
    brand: 'مبادرة من Roseleap', brandUrl: 'https://roseleap.com',
    begin: 'ابدأ', ready: 'جاهز', cycle: 'دورة', completed: 'اكتمل',
    cyclesDone: 'دورات. عمل رائع.', cycleDone: 'دورة. عمل رائع.',
  },
  uk: {
    appName: 'SafeMind', tagline: 'Ви не самотні. Допомога тут.',
    subtitle: 'Безкоштовний інструмент першої допомоги для психічного здоров\'я людей, постраждалих від конфліктів та криз.',
    moodQ: 'Як ви зараз себе почуваєте?',
    moods: ['Наляканий', 'Тривожний', 'Заціпенілий', 'Сумний', 'Злий', 'Сповнений надії'],
    moodEmoji: ['😨', '😰', '😶', '😢', '😠', '🌱'],
    tabs: ['Перевірка', 'Дихання', 'Заземлення', 'Скринінг', 'Ресурси'],
    tabIcons: ['💚', '🌬', '🌍', '📋', '🤝'],
    breatheDesc: 'Ця проста вправа допоможе заспокоїти нервову систему. Слідуйте за колом.',
    inhale: 'Вдих', hold: 'Затримка', exhale: 'Видих', rest: 'Відпочинок',
    start: 'Почати дихання', stop: 'Пауза',
    groundDesc: 'Ця техніка допомагає повернутися до поточного моменту, коли ви відчуваєте себе пригніченим.',
    groundSteps: [
      { n: 5, sense: 'речей, які ви БАЧИТЕ', icon: '👁' }, { n: 4, sense: 'речей, які ви ВІДЧУВАЄТЕ', icon: '✋' },
      { n: 3, sense: 'речей, які ви ЧУЄТЕ', icon: '👂' }, { n: 2, sense: 'речей, які ви НЮХАЄТЕ', icon: '👃' },
      { n: 1, sense: 'річ, яку ви СМАКУЄТЕ', icon: '👅' },
    ],
    groundPlaceholder: 'Напишіть, що ви помічаєте...', groundNext: 'Далі →', groundComplete: '✓ Завершено',
    groundDone: 'Чудово. Ви тут. Ви в безпеці в цю мить.', groundTryAgain: 'Спробувати знову', groundName: 'Назвіть',
    screenDesc: 'Ці питання допоможуть зрозуміти, що ви переживаєте. Немає неправильних відповідей.',
    screenQuestions: [
      'Чи маєте ви проблеми зі сном або кошмари?', 'Чи відчуваєте ви нервозність або легко лякаєтеся?',
      'Чи уникаєте ви місць, що нагадують про травматичну подію?', 'Чи відчуваєте ви емоційне заціпеніння?',
      'Чи переживаєте ви флешбеки або нав\'язливі спогади?', 'Чи відчуваєте ви безнадійність щодо майбутнього?',
      'Чи втратили ви інтерес до занять, які раніше приносили задоволення?', 'Чи важко вам зосередитися?',
    ],
    screenOptions: ['Ніколи', 'Іноді', 'Часто', 'Завжди'], screenSubmit: 'Переглянути результати', screenRetake: 'Пройти знову',
    screenLow: 'Ваші відповіді свідчать, що ви справляєтеся добре. Продовжуйте піклуватися про себе.',
    screenMid: 'Ваші відповіді свідчать про помірний стрес. Рекомендуємо звернутися до спеціаліста.',
    screenHigh: 'Ваші відповіді свідчать про значний стрес. Будь ласка, зверніться до спеціаліста або на кризову лінію.',
    viewResources: 'Переглянути ресурси →',
    resourceDesc: 'Ці організації надають безкоштовну конфіденційну підтримку.',
    resources: [
      { name: 'ВООЗ Психічне здоров\'я', desc: 'Ресурси для постраждалих від криз', url: 'https://www.who.int/health-topics/mental-health' },
      { name: 'УВКБ ООН', desc: 'Підтримка психічного здоров\'я для біженців', url: 'https://www.unhcr.org/mental-health' },
      { name: 'Лінія кризової допомоги', desc: 'Безкоштовна цілодобова підтримка', url: 'https://www.crisistextline.org', phone: 'Надішліть HOME на 741741' },
      { name: 'Міжнародний медичний корпус', desc: 'Програми в зонах конфліктів', url: 'https://internationalmedicalcorps.org' },
      { name: 'Лікарі без кордонів', desc: 'Психологічна підтримка', url: 'https://www.msf.org' },
      { name: 'Рекомендації IASC', desc: 'Психічне здоров\'я в надзвичайних ситуаціях', url: 'https://interagencystandingcommittee.org' },
    ],
    safetyNotice: 'Якщо вам загрожує небезпека, зверніться до служб екстреної допомоги.',
    crisisLine: 'Кризова підтримка доступна цілодобово',
    checkinResponse: {
      0: 'Страх — це природна реакція на небезпеку. Ви проявляєте мужність. Давайте працювати разом.',
      1: 'Тривога може бути нестерпною, але з нею можна впоратися. Давайте спробуємо техніки для заспокоєння.',
      2: 'Заціпеніння — спосіб вашого розуму захистити вас. Це нормально. М\'які кроки допоможуть.',
      3: 'Ваш сум обґрунтований. Горе та втрата — важкий тягар. Вам не потрібно нести його на самоті.',
      4: 'Гнів — природна реакція на несправедливість. Давайте знайдемо здорові способи.',
      5: 'Надія потужна, навіть у малих кількостях. Давайте плекати це почуття разом.',
    },
    suggest: 'Ми пропонуємо спробувати:', tryLabels: ['Дихальні вправи →', 'Вправа заземлення →', 'Швидкий скринінг →', 'Поговорити з кимось →'],
    resetMood: '← Перевірити знову',
    footer: 'SafeMind не замінює професійну допомогу. У разі кризи зверніться до екстрених служб.',
    brand: 'Ініціатива Roseleap', brandUrl: 'https://roseleap.com',
    begin: 'Почати', ready: 'Готово', cycle: 'Цикл', completed: 'Завершено',
    cyclesDone: 'циклів. Чудова робота.', cycleDone: 'цикл. Чудова робота.',
  },
  es: {
    appName: 'SafeMind', tagline: 'No estás solo. La ayuda está aquí.',
    subtitle: 'Una herramienta gratuita de primera respuesta en salud mental para personas afectadas por conflictos y crisis.',
    moodQ: '¿Cómo te sientes ahora mismo?',
    moods: ['Aterrorizado', 'Ansioso', 'Entumecido', 'Triste', 'Enojado', 'Esperanzado'],
    moodEmoji: ['😨', '😰', '😶', '😢', '😠', '🌱'],
    tabs: ['Registro', 'Respirar', 'Anclaje', 'Evaluación', 'Recursos'],
    tabIcons: ['💚', '🌬', '🌍', '📋', '🤝'],
    breatheDesc: 'Este simple ejercicio puede ayudar a calmar tu sistema nervioso. Sigue el círculo.',
    inhale: 'Inhala', hold: 'Mantén', exhale: 'Exhala', rest: 'Descansa',
    start: 'Comenzar a respirar', stop: 'Pausa',
    groundDesc: 'Esta técnica te ayuda a volver al momento presente cuando te sientes abrumado.',
    groundSteps: [
      { n: 5, sense: 'cosas que puedes VER', icon: '👁' }, { n: 4, sense: 'cosas que puedes TOCAR', icon: '✋' },
      { n: 3, sense: 'cosas que puedes OÍR', icon: '👂' }, { n: 2, sense: 'cosas que puedes OLER', icon: '👃' },
      { n: 1, sense: 'cosa que puedes SABOREAR', icon: '👅' },
    ],
    groundPlaceholder: 'Escribe lo que notas...', groundNext: 'Siguiente →', groundComplete: '✓ Completado',
    groundDone: 'Bien hecho. Estás aquí. Estás seguro en este momento.', groundTryAgain: 'Intentar de nuevo', groundName: 'Nombra',
    screenDesc: 'Estas preguntas nos ayudan a entender lo que experimentas. No hay respuestas incorrectas.',
    screenQuestions: [
      '¿Tienes problemas para dormir o pesadillas?', '¿Te sientes nervioso o te sobresaltas fácilmente?',
      '¿Evitas lugares que te recuerdan un evento traumático?', '¿Te sientes emocionalmente entumecido?',
      '¿Experimentas flashbacks o recuerdos intrusivos?', '¿Te sientes sin esperanza sobre el futuro?',
      '¿Has perdido interés en actividades que solías disfrutar?', '¿Tienes dificultad para concentrarte?',
    ],
    screenOptions: ['Nunca', 'A veces', 'Frecuentemente', 'Siempre'], screenSubmit: 'Ver resultados', screenRetake: 'Repetir',
    screenLow: 'Tus respuestas sugieren que estás manejando bien. Continúa cuidándote y busca ayuda si las cosas cambian.',
    screenMid: 'Tus respuestas sugieren angustia moderada. Recomendamos conectar con un profesional de salud mental.',
    screenHigh: 'Tus respuestas sugieren angustia significativa. Por favor contacta a un profesional o línea de crisis.',
    viewResources: 'Ver recursos →',
    resourceDesc: 'Estas organizaciones brindan apoyo gratuito y confidencial.',
    resources: [
      { name: 'OMS Salud Mental', desc: 'Recursos para poblaciones afectadas por crisis', url: 'https://www.who.int/health-topics/mental-health' },
      { name: 'ACNUR Consejería', desc: 'Apoyo de salud mental para refugiados', url: 'https://www.unhcr.org/mental-health' },
      { name: 'Línea de Crisis', desc: 'Apoyo gratuito 24/7 por texto', url: 'https://www.crisistextline.org', phone: 'Envía HOME al 741741' },
      { name: 'Cuerpo Médico Internacional', desc: 'Programas en zonas de conflicto', url: 'https://internationalmedicalcorps.org' },
      { name: 'MSF Apoyo Psicológico', desc: 'Servicios de Médicos Sin Fronteras', url: 'https://www.msf.org' },
      { name: 'Directrices IASC', desc: 'Salud mental en emergencias', url: 'https://interagencystandingcommittee.org' },
    ],
    safetyNotice: 'Si estás en peligro inmediato, contacta a los servicios de emergencia locales.',
    crisisLine: 'Apoyo de crisis disponible 24/7',
    checkinResponse: {
      0: 'El miedo es una respuesta natural al peligro. Muestras valentía al estar aquí. Trabajemos juntos.',
      1: 'La ansiedad puede ser abrumadora, pero se puede manejar. Probemos técnicas para calmarte.',
      2: 'Sentirse entumecido es la forma en que tu mente te protege. Está bien. Pasos suaves pueden ayudarte.',
      3: 'Tu tristeza es válida. El dolor y la pérdida son cargas pesadas. No tienes que llevarlas solo.',
      4: 'La ira es una respuesta natural a la injusticia. Encontremos formas saludables de procesar lo que sientes.',
      5: 'La esperanza es poderosa, incluso en pequeñas cantidades. Alimentemos ese sentimiento juntos.',
    },
    suggest: 'Te sugerimos probar:', tryLabels: ['Respiración guiada →', 'Ejercicio de anclaje →', 'Evaluación rápida →', 'Hablar con alguien →'],
    resetMood: '← Registrarse de nuevo',
    footer: 'SafeMind no sustituye la atención profesional. En crisis, contacta servicios de emergencia.',
    brand: 'Una iniciativa de Roseleap', brandUrl: 'https://roseleap.com',
    begin: 'Comenzar', ready: 'Listo', cycle: 'Ciclo', completed: 'Completado',
    cyclesDone: 'ciclos. Gran trabajo.', cycleDone: 'ciclo. Gran trabajo.',
  },
  fr: {
    appName: 'SafeMind', tagline: 'Vous n\'êtes pas seul. L\'aide est là.',
    subtitle: 'Un outil gratuit de premiers secours en santé mentale pour les personnes touchées par les conflits et les crises.',
    moodQ: 'Comment vous sentez-vous en ce moment ?',
    moods: ['Terrifié', 'Anxieux', 'Engourdi', 'Triste', 'En colère', 'Plein d\'espoir'],
    moodEmoji: ['😨', '😰', '😶', '😢', '😠', '🌱'],
    tabs: ['Bilan', 'Respirer', 'Ancrage', 'Dépistage', 'Ressources'],
    tabIcons: ['💚', '🌬', '🌍', '📋', '🤝'],
    breatheDesc: 'Cet exercice simple peut aider à calmer votre système nerveux. Suivez le cercle.',
    inhale: 'Inspirez', hold: 'Retenez', exhale: 'Expirez', rest: 'Repos',
    start: 'Commencer à respirer', stop: 'Pause',
    groundDesc: 'Cette technique vous aide à revenir au moment présent quand vous vous sentez submergé.',
    groundSteps: [
      { n: 5, sense: 'choses que vous pouvez VOIR', icon: '👁' }, { n: 4, sense: 'choses que vous pouvez TOUCHER', icon: '✋' },
      { n: 3, sense: 'choses que vous pouvez ENTENDRE', icon: '👂' }, { n: 2, sense: 'choses que vous pouvez SENTIR', icon: '👃' },
      { n: 1, sense: 'chose que vous pouvez GOÛTER', icon: '👅' },
    ],
    groundPlaceholder: 'Écrivez ce que vous remarquez...', groundNext: 'Suivant →', groundComplete: '✓ Terminé',
    groundDone: 'Bravo. Vous êtes ici. Vous êtes en sécurité en ce moment.', groundTryAgain: 'Réessayer', groundName: 'Nommez',
    screenDesc: 'Ces questions nous aident à comprendre ce que vous vivez. Il n\'y a pas de mauvaises réponses.',
    screenQuestions: [
      'Avez-vous des troubles du sommeil ou des cauchemars ?', 'Vous sentez-vous sur le qui-vive ?',
      'Évitez-vous les lieux rappelant un événement traumatisant ?', 'Vous sentez-vous émotionnellement engourdi ?',
      'Vivez-vous des flashbacks ou des souvenirs intrusifs ?', 'Vous sentez-vous sans espoir pour l\'avenir ?',
      'Avez-vous perdu l\'intérêt pour des activités que vous aimiez ?', 'Avez-vous des difficultés à vous concentrer ?',
    ],
    screenOptions: ['Jamais', 'Parfois', 'Souvent', 'Toujours'], screenSubmit: 'Voir les résultats', screenRetake: 'Recommencer',
    screenLow: 'Vos réponses suggèrent que vous gérez bien. Continuez à prendre soin de vous.',
    screenMid: 'Vos réponses suggèrent une détresse modérée. Nous recommandons de consulter un professionnel.',
    screenHigh: 'Vos réponses suggèrent une détresse importante. Veuillez contacter un professionnel ou une ligne de crise.',
    viewResources: 'Voir les ressources →',
    resourceDesc: 'Ces organisations offrent un soutien gratuit et confidentiel.',
    resources: [
      { name: 'OMS Santé Mentale', desc: 'Ressources pour les populations affectées par les crises', url: 'https://www.who.int/health-topics/mental-health' },
      { name: 'HCR Conseil', desc: 'Soutien en santé mentale pour les réfugiés', url: 'https://www.unhcr.org/mental-health' },
      { name: 'Ligne de Crise', desc: 'Soutien gratuit 24h/24', url: 'https://www.crisistextline.org', phone: 'Envoyez HOME au 741741' },
      { name: 'Corps Médical International', desc: 'Programmes en zones de conflit', url: 'https://internationalmedicalcorps.org' },
      { name: 'MSF Soutien Psychologique', desc: 'Services de Médecins Sans Frontières', url: 'https://www.msf.org' },
      { name: 'Directives du CPI', desc: 'Santé mentale dans les situations d\'urgence', url: 'https://interagencystandingcommittee.org' },
    ],
    safetyNotice: 'Si vous êtes en danger immédiat, contactez les services d\'urgence locaux.',
    crisisLine: 'Soutien de crise disponible 24h/24',
    checkinResponse: {
      0: 'La peur est une réponse naturelle au danger. Vous faites preuve de courage. Travaillons ensemble.',
      1: 'L\'anxiété peut être accablante, mais elle peut être gérée. Essayons des techniques pour vous calmer.',
      2: 'Se sentir engourdi est la façon dont votre esprit vous protège. C\'est normal. Des pas doux peuvent aider.',
      3: 'Votre tristesse est légitime. Le deuil et la perte sont de lourds fardeaux. Vous n\'êtes pas seul.',
      4: 'La colère est une réponse naturelle à l\'injustice. Trouvons des moyens sains de la traiter.',
      5: 'L\'espoir est puissant, même en petites quantités. Nourrissons ce sentiment ensemble.',
    },
    suggest: 'Nous vous suggérons d\'essayer :', tryLabels: ['Respiration guidée →', 'Exercice d\'ancrage →', 'Dépistage rapide →', 'Parler à quelqu\'un →'],
    resetMood: '← Refaire le bilan',
    footer: 'SafeMind ne remplace pas les soins professionnels. En cas de crise, contactez les services d\'urgence.',
    brand: 'Une initiative Roseleap', brandUrl: 'https://roseleap.com',
    begin: 'Commencer', ready: 'Prêt', cycle: 'Cycle', completed: 'Terminé',
    cyclesDone: 'cycles. Excellent travail.', cycleDone: 'cycle. Excellent travail.',
  },
  tr: {
    appName: 'SafeMind', tagline: 'Yalnız değilsiniz. Yardım burada.',
    subtitle: 'Çatışma ve krizden etkilenen insanlar için ücretsiz ruh sağlığı ilk müdahale aracı.',
    moodQ: 'Şu anda nasıl hissediyorsunuz?',
    moods: ['Dehşete düşmüş', 'Endişeli', 'Hissiz', 'Üzgün', 'Kızgın', 'Umutlu'],
    moodEmoji: ['😨', '😰', '😶', '😢', '😠', '🌱'],
    tabs: ['Kontrol', 'Nefes', 'Topraklama', 'Tarama', 'Kaynaklar'],
    tabIcons: ['💚', '🌬', '🌍', '📋', '🤝'],
    breatheDesc: 'Bu basit egzersiz sinir sisteminizi sakinleştirmeye yardımcı olabilir. Daireyi takip edin.',
    inhale: 'Nefes Al', hold: 'Tut', exhale: 'Nefes Ver', rest: 'Dinlen',
    start: 'Nefes Almaya Başla', stop: 'Duraklat',
    groundDesc: 'Bu teknik, kendinizi bunalmış hissettiğinizde şu ana dönmenize yardımcı olur.',
    groundSteps: [
      { n: 5, sense: 'GÖREBİLECEĞİNİZ şey', icon: '👁' }, { n: 4, sense: 'DOKUNABİLECEĞİNİZ şey', icon: '✋' },
      { n: 3, sense: 'DUYABİLECEĞİNİZ şey', icon: '👂' }, { n: 2, sense: 'KOKLAYABİLECEĞİNİZ şey', icon: '👃' },
      { n: 1, sense: 'TADABİLECEĞİNİZ şey', icon: '👅' },
    ],
    groundPlaceholder: 'Fark ettiklerinizi yazın...', groundNext: 'Sonraki →', groundComplete: '✓ Tamamlandı',
    groundDone: 'Aferin. Buradasınız. Bu anda güvendesiniz.', groundTryAgain: 'Tekrar Dene', groundName: 'Sayın',
    screenDesc: 'Bu sorular yaşadıklarınızı anlamamıza yardımcı olur. Yanlış cevap yoktur.',
    screenQuestions: [
      'Uyku probleminiz veya kabuslarınız var mı?', 'Gergin hissediyor veya kolayca irkiliyor musunuz?',
      'Travmatik olayı hatırlatan durumlardan kaçınıyor musunuz?', 'Duygusal olarak hissiz hissediyor musunuz?',
      'Flashback veya müdahaleci anılar yaşıyor musunuz?', 'Gelecek hakkında umutsuz hissediyor musunuz?',
      'Eskiden zevk aldığınız aktivitelere ilginizi kaybettiniz mi?', 'Konsantre olmakta zorluk çekiyor musunuz?',
    ],
    screenOptions: ['Asla', 'Bazen', 'Sık sık', 'Her zaman'], screenSubmit: 'Sonuçları Gör', screenRetake: 'Tekrarla',
    screenLow: 'Yanıtlarınız iyi başa çıktığınızı gösteriyor. Kendinize bakmaya devam edin.',
    screenMid: 'Yanıtlarınız orta düzeyde sıkıntı gösteriyor. Bir ruh sağlığı uzmanına başvurmanızı öneririz.',
    screenHigh: 'Yanıtlarınız önemli düzeyde sıkıntı gösteriyor. Lütfen bir uzmana veya kriz hattına ulaşın.',
    viewResources: 'Kaynakları Gör →',
    resourceDesc: 'Bu kuruluşlar ücretsiz ve gizli destek sağlar.',
    resources: [
      { name: 'DSÖ Ruh Sağlığı', desc: 'Krizden etkilenen nüfuslar için kaynaklar', url: 'https://www.who.int/health-topics/mental-health' },
      { name: 'BMMYK Danışmanlık', desc: 'Mülteciler için ruh sağlığı desteği', url: 'https://www.unhcr.org/mental-health' },
      { name: 'Kriz Hattı', desc: 'Ücretsiz 7/24 kriz desteği', url: 'https://www.crisistextline.org', phone: 'HOME yazıp 741741\'e gönderin' },
      { name: 'Uluslararası Tıp Birliği', desc: 'Çatışma bölgelerinde programlar', url: 'https://internationalmedicalcorps.org' },
      { name: 'MSF Psikolojik Destek', desc: 'Sınır Tanımayan Doktorlar hizmetleri', url: 'https://www.msf.org' },
      { name: 'IASC Kılavuzları', desc: 'Acil durumlarda ruh sağlığı', url: 'https://interagencystandingcommittee.org' },
    ],
    safetyNotice: 'Acil tehlike altındaysanız, lütfen yerel acil servisleri arayın.',
    crisisLine: 'Kriz desteği 7/24 mevcuttur',
    checkinResponse: {
      0: 'Korku, tehlikeye doğal bir yanıttır. Burada olarak cesaret gösteriyorsunuz. Birlikte çalışalım.',
      1: 'Kaygı bunaltıcı olabilir ama yönetilebilir. Sakinleşmek için teknikler deneyelim.',
      2: 'Hissizlik, zihninizin sizi korumasının yoludur. Sorun yok. Nazik adımlar yardımcı olabilir.',
      3: 'Üzüntünüz geçerlidir. Yas ve kayıp ağır yüklerdir. Tek başınıza taşımak zorunda değilsiniz.',
      4: 'Öfke, adaletsizliğe doğal bir yanıttır. Sağlıklı yollar bulalım.',
      5: 'Umut güçlüdür, küçük miktarlarda bile. Bu duyguyu birlikte besleyelim.',
    },
    suggest: 'Denemenizi öneriyoruz:', tryLabels: ['Nefes Rehberliği →', 'Topraklama Egzersizi →', 'Hızlı Tarama →', 'Biriyle Konuşun →'],
    resetMood: '← Tekrar kontrol et',
    footer: 'SafeMind profesyonel bakımın yerini tutmaz. Kriz durumunda acil servisleri arayın.',
    brand: 'Bir Roseleap Girişimi', brandUrl: 'https://roseleap.com',
    begin: 'Başla', ready: 'Hazır', cycle: 'Döngü', completed: 'Tamamlandı',
    cyclesDone: 'döngü. Harika iş.', cycleDone: 'döngü. Harika iş.',
  },
  hi: {
    appName: 'SafeMind', tagline: 'आप अकेले नहीं हैं। मदद यहाँ है।',
    subtitle: 'संघर्ष और संकट से प्रभावित लोगों के लिए एक मुफ्त मानसिक स्वास्थ्य प्राथमिक चिकित्सा उपकरण।',
    moodQ: 'आप अभी कैसा महसूस कर रहे हैं?',
    moods: ['भयभीत', 'चिंतित', 'सुन्न', 'उदास', 'गुस्सा', 'आशावान'],
    moodEmoji: ['😨', '😰', '😶', '😢', '😠', '🌱'],
    tabs: ['जाँच', 'साँस', 'ग्राउंडिंग', 'स्क्रीनिंग', 'संसाधन'],
    tabIcons: ['💚', '🌬', '🌍', '📋', '🤝'],
    breatheDesc: 'यह सरल व्यायाम आपकी तंत्रिका तंत्र को शांत करने में मदद कर सकता है। वृत्त का अनुसरण करें।',
    inhale: 'साँस लें', hold: 'रोकें', exhale: 'साँस छोड़ें', rest: 'आराम',
    start: 'साँस लेना शुरू करें', stop: 'रुकें',
    groundDesc: 'यह तकनीक आपको वर्तमान क्षण में वापस लाने में मदद करती है जब आप अभिभूत महसूस करते हैं।',
    groundSteps: [
      { n: 5, sense: 'चीज़ें जो आप देख सकते हैं', icon: '👁' }, { n: 4, sense: 'चीज़ें जो आप छू सकते हैं', icon: '✋' },
      { n: 3, sense: 'चीज़ें जो आप सुन सकते हैं', icon: '👂' }, { n: 2, sense: 'चीज़ें जो आप सूंघ सकते हैं', icon: '👃' },
      { n: 1, sense: 'चीज़ जो आप चख सकते हैं', icon: '👅' },
    ],
    groundPlaceholder: 'जो आप नोटिस करते हैं वह लिखें...', groundNext: 'अगला →', groundComplete: '✓ पूरा हुआ',
    groundDone: 'शाबाश। आप यहाँ हैं। इस पल में आप सुरक्षित हैं।', groundTryAgain: 'फिर से कोशिश करें', groundName: 'बताएं',
    screenDesc: 'ये प्रश्न हमें समझने में मदद करते हैं कि आप क्या अनुभव कर रहे हैं। कोई गलत उत्तर नहीं है।',
    screenQuestions: [
      'क्या आपको सोने में परेशानी होती है या बुरे सपने आते हैं?', 'क्या आप तनाव में रहते हैं या आसानी से चौंक जाते हैं?',
      'क्या आप उन जगहों या स्थितियों से बचते हैं जो किसी दर्दनाक घटना की याद दिलाती हैं?', 'क्या आप भावनात्मक रूप से सुन्न या दूसरों से अलग महसूस करते हैं?',
      'क्या आपको फ्लैशबैक या अनचाही यादें आती हैं?', 'क्या आप भविष्य के बारे में निराश महसूस करते हैं?',
      'क्या आपने उन गतिविधियों में रुचि खो दी है जिनमें आपको पहले आनंद आता था?', 'क्या आपको ध्यान केंद्रित करने में कठिनाई होती है?',
    ],
    screenOptions: ['कभी नहीं', 'कभी-कभी', 'अक्सर', 'हमेशा'], screenSubmit: 'परिणाम देखें', screenRetake: 'दोबारा करें',
    screenLow: 'आपके उत्तर बताते हैं कि आप अपेक्षाकृत अच्छी तरह से सामना कर रहे हैं। अपना ख्याल रखते रहें।',
    screenMid: 'आपके उत्तर मध्यम तनाव का संकेत देते हैं। हम एक मानसिक स्वास्थ्य पेशेवर से संपर्क करने की सलाह देते हैं।',
    screenHigh: 'आपके उत्तर गंभीर तनाव का संकेत देते हैं। कृपया किसी पेशेवर या संकट हेल्पलाइन से संपर्क करें। आप सहायता के पात्र हैं।',
    viewResources: 'संसाधन देखें →',
    resourceDesc: 'ये संगठन मुफ्त, गोपनीय सहायता प्रदान करते हैं।',
    resources: [
      { name: 'WHO मानसिक स्वास्थ्य', desc: 'संकट से प्रभावित आबादी के लिए संसाधन', url: 'https://www.who.int/health-topics/mental-health' },
      { name: 'UNHCR परामर्श', desc: 'शरणार्थियों के लिए मानसिक स्वास्थ्य सहायता', url: 'https://www.unhcr.org/mental-health' },
      { name: 'iCall (भारत)', desc: 'मुफ्त मानसिक स्वास्थ्य परामर्श', url: 'https://icallhelpline.org', phone: '9152987821' },
      { name: 'Vandrevala Foundation', desc: 'भारत में 24/7 मानसिक स्वास्थ्य हेल्पलाइन', url: 'https://vandrevalafoundation.com', phone: '1860-2662-345' },
      { name: 'MSF मनोवैज्ञानिक सहायता', desc: 'डॉक्टर्स विदाउट बॉर्डर्स सेवाएं', url: 'https://www.msf.org' },
      { name: 'IASC दिशानिर्देश', desc: 'आपातकालीन स्थितियों में मानसिक स्वास्थ्य', url: 'https://interagencystandingcommittee.org' },
    ],
    safetyNotice: 'यदि आप तत्काल खतरे में हैं, तो कृपया स्थानीय आपातकालीन सेवाओं से संपर्क करें।',
    crisisLine: 'संकट सहायता 24/7 उपलब्ध',
    checkinResponse: {
      0: 'डर खतरे के प्रति एक स्वाभाविक प्रतिक्रिया है। यहाँ आकर आप साहस दिखा रहे हैं। आइए साथ मिलकर काम करें।',
      1: 'चिंता भारी लग सकती है, लेकिन इसे संभाला जा सकता है। आइए शरीर और मन को शांत करने की तकनीकें आज़माएं।',
      2: 'सुन्न महसूस करना आपके मन का आपको बचाने का तरीका है। यह ठीक है। धीरे-धीरे फिर से जुड़ने में मदद मिल सकती है।',
      3: 'आपकी उदासी वैध है। दुख और नुकसान भारी बोझ हैं। आपको इसे अकेले नहीं उठाना है।',
      4: 'गुस्सा अन्याय के प्रति एक स्वाभाविक प्रतिक्रिया है। आइए स्वस्थ तरीके खोजें।',
      5: 'उम्मीद शक्तिशाली है, छोटी मात्रा में भी। आइए इस भावना को साथ मिलकर पोषित करें।',
    },
    suggest: 'हम सुझाव देते हैं:', tryLabels: ['निर्देशित श्वास →', 'ग्राउंडिंग व्यायाम →', 'त्वरित जाँच →', 'किसी से बात करें →'],
    resetMood: '← फिर से जाँचें',
    footer: 'SafeMind पेशेवर देखभाल का विकल्प नहीं है। संकट में आपातकालीन सेवाओं से संपर्क करें।',
    brand: 'एक Roseleap पहल', brandUrl: 'https://roseleap.com',
    begin: 'शुरू करें', ready: 'तैयार', cycle: 'चक्र', completed: 'पूरा हुआ',
    cyclesDone: 'चक्र। बहुत अच्छा।', cycleDone: 'चक्र। बहुत अच्छा।',
  },
  tl: {
    appName: 'SafeMind', tagline: 'Hindi ka nag-iisa. Nandito ang tulong.',
    subtitle: 'Isang libreng mental health first-response tool para sa mga taong apektado ng digmaan at krisis.',
    moodQ: 'Ano ang nararamdaman mo ngayon?',
    moods: ['Takot na takot', 'Balisa', 'Manhid', 'Malungkot', 'Galit', 'May pag-asa'],
    moodEmoji: ['😨', '😰', '😶', '😢', '😠', '🌱'],
    tabs: ['Pag-check', 'Paghinga', 'Grounding', 'Screening', 'Mga Tulong'],
    tabIcons: ['💚', '🌬', '🌍', '📋', '🤝'],
    breatheDesc: 'Ang simpleng ehersisyo na ito ay makakatulong na pakalmahin ang iyong nervous system. Sundan ang bilog.',
    inhale: 'Huminga', hold: 'Hawakan', exhale: 'Ilabas', rest: 'Pahinga',
    start: 'Simulan ang Paghinga', stop: 'Ihinto',
    groundDesc: 'Ang teknik na ito ay tumutulong sa iyo na bumalik sa kasalukuyang sandali kapag nalulula ka.',
    groundSteps: [
      { n: 5, sense: 'bagay na NAKIKITA mo', icon: '👁' }, { n: 4, sense: 'bagay na NAHAHAWAKAN mo', icon: '✋' },
      { n: 3, sense: 'bagay na NARIRINIG mo', icon: '👂' }, { n: 2, sense: 'bagay na NAAMOY mo', icon: '👃' },
      { n: 1, sense: 'bagay na NALALASAHAN mo', icon: '👅' },
    ],
    groundPlaceholder: 'Isulat ang napapansin mo...', groundNext: 'Susunod →', groundComplete: '✓ Tapos na',
    groundDone: 'Magaling. Nandito ka. Ligtas ka sa sandaling ito.', groundTryAgain: 'Subukan Muli', groundName: 'Pangalanan',
    screenDesc: 'Ang mga tanong na ito ay tumutulong sa amin na maunawaan ang iyong nararanasan. Walang maling sagot.',
    screenQuestions: [
      'Nahihirapan ka bang matulog o nagkakaroon ng mga bangungot?', 'Pakiramdam mo ba ay laging alerto o madaling magulat?',
      'Iniiwasan mo ba ang mga lugar o sitwasyon na nagpapaalala sa isang traumatikong pangyayari?', 'Nararamdaman mo ba na manhid o malayo sa iba?',
      'Nakakaranas ka ba ng mga flashback o biglang mga alaala?', 'Nararamdaman mo ba na walang pag-asa ang kinabukasan?',
      'Nawalan ka ba ng interes sa mga aktibidad na dati mong nae-enjoy?', 'Nahihirapan ka bang mag-concentrate?',
    ],
    screenOptions: ['Hindi kailanman', 'Minsan', 'Madalas', 'Palagi'], screenSubmit: 'Tingnan ang Resulta', screenRetake: 'Ulitin',
    screenLow: 'Ipinapakita ng mga sagot mo na medyo maayos ka pa. Patuloy na alagaan ang sarili at humingi ng tulong kung magbago ang mga bagay.',
    screenMid: 'Ipinapakita ng mga sagot mo ang katamtamang pagkabalisa. Inirerekomenda naming kumonekta sa isang mental health professional.',
    screenHigh: 'Ipinapakita ng mga sagot mo ang matinding pagkabalisa. Mangyaring makipag-ugnayan sa isang propesyonal o crisis line. Karapat-dapat ka sa suporta.',
    viewResources: 'Tingnan ang Mga Tulong →',
    resourceDesc: 'Ang mga organisasyong ito ay nagbibigay ng libre at kumpidensyal na suporta.',
    resources: [
      { name: 'WHO Mental Health', desc: 'Mga mapagkukunan para sa mga apektado ng krisis', url: 'https://www.who.int/health-topics/mental-health' },
      { name: 'UNHCR Counseling', desc: 'Mental health support para sa mga refugee', url: 'https://www.unhcr.org/mental-health' },
      { name: 'NCMH Crisis Hotline (Pilipinas)', desc: 'Libreng 24/7 crisis support', url: 'https://ncmh.gov.ph', phone: '0966-351-4518' },
      { name: 'Hopeline PH', desc: 'Libreng suicide prevention hotline', url: 'https://www.hopeline.ph', phone: '0917-558-4673' },
      { name: 'MSF Psychological Support', desc: 'Mga serbisyo ng Doctors Without Borders', url: 'https://www.msf.org' },
      { name: 'IASC Guidelines', desc: 'Mental health sa mga emergency', url: 'https://interagencystandingcommittee.org' },
    ],
    safetyNotice: 'Kung ikaw ay nasa agarang panganib, mangyaring makipag-ugnayan sa lokal na emergency services.',
    crisisLine: 'Crisis support available 24/7',
    checkinResponse: {
      0: 'Ang takot ay natural na tugon sa panganib. Nagpapakita ka ng tapang sa pag-punta rito. Magtulungan tayo.',
      1: 'Ang pagkabalisa ay maaaring nakakalula, ngunit maaari itong kontrolin. Subukan natin ang mga teknik para pakalmahin ka.',
      2: 'Ang pagiging manhid ay paraan ng iyong isip para protektahan ka. Okay lang. Dahan-dahang hakbang ang makakatulong.',
      3: 'Valid ang iyong kalungkutan. Ang pagdadalamhati at pagkawala ay mabigat na pasanin. Hindi mo kailangang buhatin mag-isa.',
      4: 'Ang galit ay natural na tugon sa kawalan ng katarungan. Maghanap tayo ng malusog na paraan para harapin ito.',
      5: 'Ang pag-asa ay makapangyarihan, kahit sa maliit na dami. Alagaan natin ang damdaming ito nang magkasama.',
    },
    suggest: 'Iminumungkahi naming subukan:', tryLabels: ['Guided na Paghinga →', 'Grounding Exercise →', 'Mabilis na Screening →', 'Kausapin ang Isang Tao →'],
    resetMood: '← Mag-check muli',
    footer: 'Ang SafeMind ay hindi kapalit ng propesyonal na pangangalaga. Sa krisis, tumawag sa emergency services.',
    brand: 'Isang Roseleap Initiative', brandUrl: 'https://roseleap.com',
    begin: 'Magsimula', ready: 'Handa', cycle: 'Siklo', completed: 'Nakumpleto',
    cyclesDone: 'siklo. Magaling!', cycleDone: 'siklo. Magaling!',
  },
};

export function t(key, lang = 'en') {
  const tr = TRANSLATIONS[lang] || TRANSLATIONS.en;
  return tr[key] !== undefined ? tr[key] : TRANSLATIONS.en[key];
}

export const T = TRANSLATIONS.en;

export const styles = {
  sectionDesc: { color: '#5a6e5a', fontSize: 15, lineHeight: 1.7, maxWidth: 420, margin: '0 auto 28px', textAlign: 'center' },
  card: { background: 'rgba(255,255,255,0.45)', borderRadius: 18, padding: 28, maxWidth: 420, margin: '0 auto', border: '1px solid rgba(139,176,132,0.12)', backdropFilter: 'blur(8px)' },
  textarea: { width: '100%', padding: 14, borderRadius: 12, border: '1px solid rgba(139,176,132,0.25)', background: 'rgba(255,255,255,0.6)', resize: 'none', fontSize: 14, color: '#3a5a35', boxSizing: 'border-box', fontFamily: "'DM Sans', sans-serif", lineHeight: 1.6 },
  primaryBtn: { padding: '13px 36px', borderRadius: 28, border: 'none', cursor: 'pointer', background: 'linear-gradient(135deg, #7aaa6e 0%, #5a8e52 100%)', color: '#fff', fontSize: 15, fontWeight: 700, letterSpacing: 0.3, boxShadow: '0 4px 16px rgba(90,142,82,0.2)', transition: 'all 0.3s' },
  secondaryBtn: { padding: '10px 22px', borderRadius: 24, cursor: 'pointer', border: '1.5px solid rgba(122,170,110,0.3)', background: 'rgba(255,255,255,0.5)', color: '#3a6a30', fontSize: 14, fontWeight: 600, transition: 'all 0.25s' },
  linkBtn: { background: 'none', border: 'none', cursor: 'pointer', color: '#7aaa6e', fontSize: 13, fontWeight: 600, padding: 0 },
};
